// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFJyX5bZE4iOdnO90wgd2OMvHH_DyUkmY',
    appId: '1:504902716848:web:eb8aed1ebbbf7d9d169a75',
    messagingSenderId: '504902716848',
    projectId: 'flutter-spo',
    authDomain: 'flutter-spo.firebaseapp.com',
    storageBucket: 'flutter-spo.appspot.com',
    measurementId: 'G-NZL92C4S38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkXaD3gm5CxMNvV7lpm-fP2vRY4-XnUxg',
    appId: '1:504902716848:android:3f244d376e9074ce169a75',
    messagingSenderId: '504902716848',
    projectId: 'flutter-spo',
    storageBucket: 'flutter-spo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVIWgns5vBRinNAFXWgDLrKjLi0ENOYAM',
    appId: '1:504902716848:ios:71182e4ee2a75f85169a75',
    messagingSenderId: '504902716848',
    projectId: 'flutter-spo',
    storageBucket: 'flutter-spo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVIWgns5vBRinNAFXWgDLrKjLi0ENOYAM',
    appId: '1:504902716848:ios:4dc106156d5ced77169a75',
    messagingSenderId: '504902716848',
    projectId: 'flutter-spo',
    storageBucket: 'flutter-spo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
